# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build and Test

on:
  push:
    tags: "*.*.*"

jobs:
  tag_info:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.get_tag_name.outputs.tag_name }}  }}
      tag_message: ${{ steps.get_tag_message.outputs.tag_message }}
    steps:
    - name: Add Git Identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get last tag name
      id: get_tag_name
      run: |
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"
        echo "tag_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        
    - name: Print tag name
      run: |
        echo "Tag Name: ${{ steps.get_tag_name.outputs.tag_name }}"

        # - name: Get tag message
        #   id: get_tag_message
        #   run: |
        #     msg=git tag -l ${{ steps.get_tag_name.outcome.tag_name }} --format '%(contents)')
        #     echo "tag_message=$msg" >> $GITHUB_OUTPUT

    - name: Alternative way to get tag message
      id: get_tag_message
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        tm=$(git tag -l --format='%(contents:subject)' ${{ steps.get_tag_name.outputs.tag_name }})
        echo "Tag Message: $tm"
        echo "tag_message=$tm" >> $GITHUB_OUTPUT

    - name: Print tag message
      run: |
        echo "Tag Message: $TAG_MESSAGE"

    - name: Print Outputs
      run: |
        echo "Tag Name: ${{ steps.get_tag_name.outputs.tag_name }}"
        echo "Tag Message: ${{ steps.get_tag_message.outputs.tag_message }}"
        echo "tag_message=$(git tag -l 0.1.3 --format='%(contents)')"
