name: Create Release

on:
    push:
        tags:
            - '*.*.*'

env:
    LAST_TAG_NAME: ""
    LAST_TAG_MESSAGE: ""

jobs:
    get_tag_info:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Get last tag name
          run: echo "LAST_TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
        - name: Get last tag message
          run: echo "LAST_TAG_MESSAGE=$(git tag -l --format='%(contents:subject)' ${{ env.LAST_TAG_NAME }})" >> $GITHUB_ENV
        outputs:
            tag_name: ${{ env.LAST_TAG_NAME }}
            tag_message: ${{ env.LAST_TAG_MESSAGE }}

    check_pods:
        needs: get_tag_info
        runs-on: macos-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup Ruby
          uses: ruby/setup-ruby@v1
          with: 
            ruby-version: 2.7
        - name: Install CocoaPods
          run: gem install cocoapods
        - name: Deploy HelloAutomation.podspec to Cocoapods
          run: |
            set -eo pipefail
            pod lib lint HelloAutomation.podspec --allow-warnings
            pod trunk push HelloAutomation.podspec --allow-warnings
          env:
            COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        - name: Deploy .podspec to Cocoapods
          run: |
            set -eo pipefail
            pod lib lint Helper.podspec --allow-warnings
            pod trunk push Helper.podspec --allow-warnings
          env:
            COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}


    create_release:
        permissions:
            contents: write
        needs: get_tag_info
        runs-on: ubuntu-latest
        steps:
        - name: Create Release
          uses: actions/create-release@v1
          env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
                tag_name: ${{ needs.get_tag_info.outputs.tag_name }}
                release_name: Release ${{ needs.get_tag_info.outputs.tag_name }}
                body: ${{ needs.get_tag_info.outputs.tag_message }}


