# Publish CocoaPods podspec
# -------------------------

name: Publish CocoaPods
on:
    push:
      tags:
        - '*.*.*'
    workflow_dispatch:
env:
  LAST_TAG: ${GITHUB_REF#refs/*/}
  LAST_TAG_MSG: ${git show -s --format=%s ${ env.LAST_TAG }}

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Last Tag
          run: echo ${{ env.LAST_TAG }}
        - name: Get Last Tag Message
          run: |
            env.LAST_TAG_MSG=$(git show -s --format=%s ${{ env.LAST_TAG }})
        - name: Print Message
          run: echo ${{ env.LAST_TAG_MSG }}